---
title: "STAT 331: Final Project"
author: "Ethan Handelman, Maxwell Dubow, Aaron Eliscu"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

## Setup

```{r setup}
library(tidyverse)
library(knitr)

life_expectancy <- read_csv("Data/lex.csv")
coal_per_cap <- read_csv("Data/coal_consumption_per_cap.csv",
           na = c("NA", ""))

```

## Pivoting/Joining the Data

```{r}
life_expectancy <- life_expectancy |>
  pivot_longer(cols = 2:last_col(),
    names_to = "year",
    values_to = "infant_lex")

coal_per_cap <- coal_per_cap |>
  mutate(across(.cols = 2:last_col(), as.double)) |>
  pivot_longer(cols = 2:last_col(),
               names_to = "year",
               values_to = "coal_cons_per_cap")

lex_coal <- coal_per_cap |>
  left_join(life_expectancy, by = c("country", "year"))
```

## Data Description

In this investigative report we will be comparing two quantitative variables across countries/years:

- **Coal consumption per capita (measured in tonnes oil equivalent)**

    Source: [BP Statistical Review](https://www.bp.com/statisticalreview)
- **Infant life expectancy**

    Source: [Gapminder](https://www.gapminder.org/data/documentation/gd004/)

## Hypothesis